# Generated by Django 5.0.6 on 2026-05-01 03:33

import apps.shipping.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('address', models.TextField(help_text='Full shipping address details')),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('SHIPPING', 'Shipping'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], default='PROCESSING', max_length=20)),
                ('tracking_number', models.CharField(default=apps.shipping.models.generate_tracking_number, max_length=50, unique=True)),
                ('estimated_delivery', models.DateTimeField(default=apps.shipping.models.default_estimated_delivery)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shipments',
                'ordering': ['-created_at'],
            },
        ),
    ]
