# Generated by Django 5.0.6 on 2026-06-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('SHIPPING', 'Shipping'), ('DELIVERED', 'Delivered')], default='PROCESSING', max_length=20),
        ),
    ]
