# Generated by Django 5.0.6 on 2026-05-01 03:32

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('description', models.TextField(blank=True)),
                ('seller_id', models.UUIDField(db_index=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='VND', max_length=3)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=10)),
                ('stock_status', models.CharField(choices=[('in_stock', 'In Stock'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('discontinued', 'Discontinued')], default='out_of_stock', max_length=20)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, help_text='kg', max_digits=8, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, help_text='cm', max_digits=8, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, help_text='cm', max_digits=8, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='cm', max_digits=8, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'product_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('isbn', models.CharField(db_index=True, max_length=13, unique=True)),
                ('author', models.CharField(max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('pages', models.PositiveIntegerField(blank=True, null=True)),
                ('language', models.CharField(default='vi', max_length=10)),
                ('genre', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'products_books',
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='ElectronicsProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('brand', models.CharField(max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('warranty_months', models.PositiveIntegerField(default=12)),
                ('voltage', models.CharField(blank=True, help_text='e.g. 220V', max_length=20)),
                ('connectivity', models.JSONField(blank=True, default=list, help_text='["WiFi", "Bluetooth"]')),
                ('os', models.CharField(blank=True, max_length=100)),
                ('processor', models.CharField(blank=True, max_length=200)),
                ('ram_gb', models.PositiveIntegerField(blank=True, null=True)),
                ('storage_gb', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products_electronics',
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='FashionProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unisex', 'Unisex'), ('kids', 'Kids')], default='unisex', max_length=10)),
                ('material', models.CharField(blank=True, max_length=200)),
                ('care_instructions', models.TextField(blank=True)),
                ('season', models.CharField(blank=True, help_text='Spring, Summer, etc.', max_length=50)),
            ],
            options={
                'db_table': 'products_fashion',
            },
            bases=('products.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'db_table': 'product_images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g. 'Size M - Red'", max_length=100)),
                ('sku_suffix', models.CharField(max_length=20)),
                ('price_delta', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('attributes', models.JSONField(default=dict, help_text='{"size": "M", "color": "red"}')),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'db_table': 'product_variants',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='products_sku_fe2039_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'category'], name='products_status_3f4ce6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['seller_id'], name='products_seller__c70854_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'sku_suffix')},
        ),
    ]
